"""empty message

Revision ID: 03e2c2056811
Revises: c70fe88fa30b
Create Date: 2020-12-29 09:37:53.715707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e2c2056811'
down_revision = 'c70fe88fa30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('image_file', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
