"""empty message

Revision ID: 0bdc82682ed4
Revises: 
Create Date: 2020-12-22 19:38:18.578220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bdc82682ed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
