"""empty message

Revision ID: 656d739ef9e8
Revises: 911f3de52ed1
Create Date: 2020-12-22 23:40:31.962407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '656d739ef9e8'
down_revision = '911f3de52ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=1000000.0), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
