"""empty message

Revision ID: 81997ec9a9a8
Revises: 12403d9e2961
Create Date: 2020-12-15 09:03:39.588318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81997ec9a9a8'
down_revision = '12403d9e2961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
