"""empty message

Revision ID: 911f3de52ed1
Revises: 0bdc82682ed4
Create Date: 2020-12-22 23:08:25.243878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911f3de52ed1'
down_revision = '0bdc82682ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
